### ISSUE TITLE
Clean up re-exports + pre-release tracking

### ISSUE THREAD

**Issue by ValuedMammal** [bitcoindevkit/bdk-kyoto#53]
When discussing plans to publish a release I found a few TODO items

- [ ] Decide which types to re-export
- [x] We placed the `builder` module behind a "wallet" feature, so I think also add `required-features = ["wallet"]` for the wallet example in Cargo.toml
- [x] Depend on a proper version of kyoto-cbf

**Comment by rustaceanrob** [comment]
we need the `kyoto` re-exports so a `Client` can be built without the `builder` module but all of the `rust-bitcoin` re-exports are probably not necessary

**Comment by rustaceanrob** [comment]
let's hold off on release until we chat with Steve oct 3

**Comment by rustaceanrob** [comment]
after doing a little reading, i might push back a bit on the first bullet. although it is not necessarily _encouraged_, since `kyoto` is very tightly coupled with `rust-bitcoin` types, it makes sense to re-export them imo. in an effort to never force the user to add `kyoto`, i think it makes sense to give them the types they will come across, even if re-exports from `rust-bitcoin`

**Comment by ValuedMammal** [comment]
Yeah I would agree with that as long as we can justify it as a deliberate choice on behalf of the user

**Comment by rustaceanrob** [comment]
would you consider that a doc-level thing? or in the readme?

**Comment by ValuedMammal** [comment]
I don't think you need to explain it anywhere, just that the effect is what you say, i.e. the user doesn't need to pull in extra deps.
